In [11]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import joblib
from sklearn.metrics import mean_absolute_error

In [12]:
column_names = ["sale_price","sq_feet","num_bedrooms","num_bathrooms"]
df = pd.read_csv("house_data.csv")
df.columns = column_names
df

sale_price  sq_feet  num_bedrooms  num_bathrooms
0       350000     2200             3              2
1       500000     2800             4              3
2       280000     1500             2              1
3       600000     3500             5              4
4       400000     2600             3              2
5       320000     1900             3              2
6       450000     3200             4              3
7       550000     4000             5              4
8       380000     2400             3              2
9       700000     4500             6              4
10      420000     2700             4              2
11      330000     2000             3              2
12      480000     3000             4              3
13      520000     3800             5              4
14      300000     1800             3              1
15      430000     2500             4              2

In [13]:
x = df[["sq_feet","num_bedrooms","num_bathrooms"]]
x

sq_feet  num_bedrooms  num_bathrooms
0      2200             3              2
1      2800             4              3
2      1500             2              1
3      3500             5              4
4      2600             3              2
5      1900             3              2
6      3200             4              3
7      4000             5              4
8      2400             3              2
9      4500             6              4
10     2700             4              2
11     2000             3              2
12     3000             4              3
13     3800             5              4
14     1800             3              1
15     2500             4              2

In [17]:
y = df[["sale_price"]]
y

sale_price
0       350000
1       500000
2       280000
3       600000
4       400000
5       320000
6       450000
7       550000
8       380000
9       700000
10      420000
11      330000
12      480000
13      520000
14      300000
15      430000

In [19]:
x_scaler = MinMaxScaler(feature_range = (0,1))
y_scaler =  MinMaxScaler(feature_range=(0,1))

x.loc[:,x.columns] = x_scaler.fit_transform(x[x.columns])
y.loc[:,y.columns] =y_scaler.fit_transform(y[y.columns])

C:\Users\renu4\AppData\Local\Temp\ipykernel_16920\6370906.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.23333333 0.43333333 0.         0.66666667 0.36666667 0.13333333
 0.56666667 0.83333333 0.3        1.         0.4        0.16666667
 0.5        0.76666667 0.1        0.33333333]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  x.loc[:,x.columns] = x_scaler.fit_transform(x[x.columns])
C:\Users\renu4\AppData\Local\Temp\ipykernel_16920\6370906.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.25 0.5  0.   0.75 0.25 0.25 0.5  0.75 0.25 1.   0.5  0.25 0.5  0.75
 0.25 0.5 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  x.loc[:,x.columns] = x_scaler.fit_transform(x[x.columns])
C:\Users\renu4\AppData\Local\Temp\ipykernel_16920\6370906.py:4: FutureWarning

In [21]:
x = x.to_numpy()
x

array([[0.23333333, 0.25      , 0.33333333],
       [0.43333333, 0.5       , 0.66666667],
       [0.        , 0.        , 0.        ],
       [0.66666667, 0.75      , 1.        ],
       [0.36666667, 0.25      , 0.33333333],
       [0.13333333, 0.25      , 0.33333333],
       [0.56666667, 0.5       , 0.66666667],
       [0.83333333, 0.75      , 1.        ],
       [0.3       , 0.25      , 0.33333333],
       [1.        , 1.        , 1.        ],
       [0.4       , 0.5       , 0.33333333],
       [0.16666667, 0.25      , 0.33333333],
       [0.5       , 0.5       , 0.66666667],
       [0.76666667, 0.75      , 1.        ],
       [0.1       , 0.25      , 0.        ],
       [0.33333333, 0.5       , 0.33333333]])

In [23]:
y = y.to_numpy()
y

array([[0.16666667],
       [0.52380952],
       [0.        ],
       [0.76190476],
       [0.28571429],
       [0.0952381 ],
       [0.4047619 ],
       [0.64285714],
       [0.23809524],
       [1.        ],
       [0.33333333],
       [0.11904762],
       [0.47619048],
       [0.57142857],
       [0.04761905],
       [0.35714286]])

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [27]:
y_test

array([[0.04761905],
       [0.57142857],
       [0.23809524],
       [0.52380952]])

In [29]:
model = Sequential()
model

<Sequential name=sequential, built=False>

In [31]:
model.add(Dense(50,input_dim = 3,activation = 'relu'))

C:\Users\renu4\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
model.add(Dense(100,activation='relu'))
model.add(Dense(50,activation='relu'))

In [35]:
model.add(Dense(1,activation='linear'))

In [37]:
 model.compile(
     loss='mean_squared_error',
     optimizer = 'SGD'
 )  

In [39]:
model.fit(x_train,y_train,epochs=50,batch_size=8,shuffle=True)

Epoch 1/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1571  
Epoch 2/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1428 
Epoch 3/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1149 
Epoch 4/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0905 
Epoch 5/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0666 
Epoch 6/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0716 
Epoch 7/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0633 
Epoch 8/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0392 
Epoch 9/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0442 
Epoch 10/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0450 
Epoch 11/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0318 
Epoch 12/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0342 
Epoch 13/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0334 
Epoch 14/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0330 
Epoch 15/50
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0256 
Epoch 16/50
2/2 ━━━━━━━━━━━━━━━━━

In [41]:
joblib.dump(x_scaler,"x_scaler.pkl")
joblib.dump(y_scaler,"y_scaler.pkl")

['y_scaler.pkl']

In [43]:
model.save("house_value_model.h5")

In [45]:
print("Model training results:")
predictions_train = model.predict(x_train,verbose =0)

mse_train = mean_absolute_error(y_scaler.inverse_transform(predictions_train),
                               y_scaler.inverse_transform(y_train))

print(f" - Training Set Error: {mse_train}")
     

Model training results:
 - Training Set Error: 37195.114583333336


In [49]:
predictions_test = model.predict(x_test,verbose=0)

mse_test = mean_absolute_error(y_scaler.inverse_transform(predictions_test),y_scaler.inverse_transform(y_test))

print(f" -Test error :{mse_test}")

 -Test error :32895.12500000003
